# Generated by Django 5.0.7 on 2025-03-03 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faq', '0001_initial'),
        ('property', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='morelivingfaq',
            name='user',
            field=models.ForeignKey(help_text='User who created this FAQ', on_delete=django.db.models.deletion.CASCADE, related_name='website_faqs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertyfaq',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent FAQ if this is a reply', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='faq.propertyfaq'),
        ),
        migrations.AddField(
            model_name='propertyfaq',
            name='property',
            field=models.ForeignKey(help_text='The Property to which this FAQ belongs', on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='property.property'),
        ),
        migrations.AddField(
            model_name='propertyfaq',
            name='user',
            field=models.ForeignKey(help_text='User who created this FAQ', on_delete=django.db.models.deletion.CASCADE, related_name='hotel_faqs', to=settings.AUTH_USER_MODEL),
        ),
    ]
