# Generated by Django 5.0.7 on 2025-03-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.DecimalField(decimal_places=2, help_text='Discount percentage for the offer.', max_digits=5)),
                ('start_date', models.DateField(help_text='Start date of the weekly offer.')),
                ('end_date', models.DateField(help_text='End date of the weekly offer.')),
                ('description', models.TextField(blank=True, help_text='Details about the offer.', null=True)),
            ],
        ),
    ]
