# Generated by Django 5.0.7 on 2025-03-03 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offers', '0001_initial'),
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyoffer',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_offers', to='property.property'),
        ),
        migrations.AddConstraint(
            model_name='weeklyoffer',
            constraint=models.CheckConstraint(check=models.Q(('start_date__lte', models.F('end_date'))), name='valid_offer_date_range'),
        ),
    ]
