# Generated by Django 5.0.7 on 2025-03-03 09:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_in', models.DateField(help_text='Check-in date for the booking.')),
                ('check_out', models.DateField(help_text='Check-out date for the booking.')),
                ('num_guests', models.PositiveIntegerField(help_text='Number of guests for the booking.')),
                ('customer_phone', models.CharField(blank=True, help_text='Phone number of the customer.', max_length=20, null=True)),
                ('first_name', models.CharField(blank=True, help_text='First name of the customer.', max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, help_text='Last name of the customer.', max_length=255, null=True)),
                ('customer_email', models.EmailField(help_text='Email of the customer.', max_length=254)),
                ('guest_status', models.CharField(blank=True, choices=[('checked_in', 'Checked In'), ('checked_out', 'Checked Out')], max_length=20, null=True)),
                ('booking_date', models.DateField(auto_now_add=True, help_text='Date when the booking was made.')),
                ('payment_method', models.CharField(blank=True, choices=[('cod', 'Cash on Arrival'), ('stripe', 'Stripe'), ('moredeals', 'MoreDeals')], max_length=20, null=True)),
                ('payment_status', models.CharField(blank=True, choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('pending', 'Pending')], default='pending', max_length=20, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cancellation_status', models.CharField(blank=True, choices=[('not_canceled', 'Not Canceled'), ('canceled', 'Canceled')], default='not_canceled', help_text='Indicates if the booking has been canceled.', max_length=20, null=True)),
                ('cancellation_date', models.DateField(blank=True, help_text='Date when the booking was canceled.', null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='country.country')),
            ],
        ),
    ]
