# Generated by Django 5.0.7 on 2025-03-03 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('property', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='property',
            field=models.ForeignKey(help_text='The property this booking belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='property.property'),
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(blank=True, help_text='The room type this booking is for.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='rooms.roomtype'),
        ),
    ]
