# Generated by Django 5.0.7 on 2025-03-07 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='num_rooms',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Number of rooms booked.', null=True),
        ),
    ]
