# Generated by Django 5.0.7 on 2025-03-03 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currency', '0001_initial'),
        ('property', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policy',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='property.property'),
        ),
        migrations.AddField(
            model_name='parkinginfo',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parking_info', to='property.property'),
        ),
        migrations.AddField(
            model_name='cancellationpolicy',
            name='property',
            field=models.ForeignKey(help_text='The property this cancellation policy belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_policy', to='property.property'),
        ),
        migrations.AddField(
            model_name='breakfastinfo',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakfast_info', to='property.property'),
        ),
        migrations.AddField(
            model_name='propertyamenities',
            name='amenity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='property.amenity'),
        ),
        migrations.AddField(
            model_name='propertyamenities',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='property.property'),
        ),
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='property.propertycategory'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='property.property'),
        ),
        migrations.AddField(
            model_name='singleunitprice',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='currency.currency'),
        ),
        migrations.AddField(
            model_name='singleunitprice',
            name='property',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='single_unit_price', to='property.property'),
        ),
    ]
